### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Marko259** [Vatsim-Scandinavia/events#2]
- [x] View event
- [x] Create event
- [x] Update event
- [x] Delete event
- [x] Setup
    - [x] Start time/date (UTC)
    - [x] End time/date (UTC)
    - [x] Recurring
    - [x] Title
    - [x] Description ([Refer to this package](https://github.com/GrahamCampbell/Laravel-Markdown))
    - [x] Cover img
- [ ] TBD

**Comment by blt950** [comment]
This seems completed
